export const newsConstants = {
    ADD_TO_READ_LATER: 'ADD_READ_LATER',
    REMOVE_FROM_READ_LATER: 'REMOVE_FROM_READ_LATER',
    VIEW_FROM_READ_LATER: 'VIEW_FROM_READ_LATER',
}

export const searchConstants = {
    SEARCH_NEWS: 'SEARCH_NEWS',
    REMOVE_SEARCH_ITEM: 'REMOVE_SEARCH_ITEM',
}

export const categoryConstants = {
    CATEGORY_NEWS: 'CATEGORY_NEWS',
    REMOVE_CATEGORY_ITEM: 'REMOVE_CATEGORY_ITEM',
}